name: Deploy it on two different machines

on:
  push:
    branches:
      - main

jobs:
  remote_deploy:
    runs-on: [self-hosted, local]
    steps:
      - uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker-compose down || true
          docker-compose build
          docker-compose up -d
        working-directory: ./  # change if docker-compose.yml is in subfolder

      - name: Verify deployment
        run: docker ps

