name: Deploy it on self-hosted runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker-compose down || true
          docker-compose build
          docker-compose up -d
        working-directory: ./  # adjust if docker-compose.yml is in a subfolder

      - name: Verify deployment
        run: docker ps

